### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#123]
I'm having problems fast-forwarding my local branches, probably because people are committing cr/lf characters. We need a .gitattributes file to fix this.

**Comment by matthiaskoenig** [comment]
Here some information about it
https://help.github.com/articles/dealing-with-line-endings/
The issue is probably mainly @kirichoi commits from Windows. So could you set
```
git config --global core.autocrlf true
# Configure Git on Windows to properly handle line endings
```
on your git installation until we have a .gitattributes. 

@0u812 Could you take care of the .gitattributes, I have no idea which files create problems in your fast-forwards. In addition I have no idea which files should keep windows file endings! for the windows installation of tellurium.

**Comment by 0u812** [comment]
Sure no problem!

**Comment by kirichoi** [comment]
I changed the config so hopefully there's no further problem.
