### ISSUE TITLE
tellurium crashes when bioservices is not available

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#125]
We haven't tested bioservices across all platforms yet so we don't know if it will always work or always be available. Currently, tellurium fails to import when bioservices is not present. It would be good if it was still possible to import tellurium even if bioservices is not available. @matthiaskoenig can you comment/help with this?

**Comment by matthiaskoenig** [comment]
Yes. Will implement workaround to get models directly via httplib. Is only
needed to get the sbml from biomodels.
On May 14, 2016 12:30 AM, "Kyle Medley" <notifications@github.com> wrote:

We haven't tested bioservices across all platforms yet so we don't know if
it will always work or always be available. Currently, tellurium fails to
import when bioservices is not present. It would be good if it was still
possible to import tellurium even if bioservices is not available.
@matthiaskoenig <https://github.com/matthiaskoenig> can you comment/help
with this?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/sys-bio/tellurium/issues/125>

**Comment by matthiaskoenig** [comment]
This should work now with latest commit.
I did a fallback via httplib if bioservices cannot be imported in `temiriam.py`.

bioservices is also used to resolve annotations within some notebook examples, but this should not affect the general import of tellurium.
@0u812 let me know if this solves the issue

**Comment by 0u812** [comment]
Yes this solves it. Thanks so much!
