### ISSUE TITLE
Duplicate reactions in Antimony should generate errors

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#129]
If you have two reactions with the same ID, e.g.
```
J0: A -> B; 1
J0: B -> C; 1
```
then the `loada` function will happily drop one of the reactions and run the model without errors. The output will be garbage, of course. This case should generate an error. I don't know if Antimony already posts an error which is ignored by the wrapper, hence I'm posting it here.

**Comment by luciansmith** [comment]
Because of the way elements from submodels can be replaced, Antimony will
always let you redefine a previously-defined element, even within the same
model.  If you say
p1 = 1
p1 = 2

then p1 will equal 2.  This is so that you can load a submodel, and then
change the values:

A: submod1(p1, p2, p3)
p1  = 2

Whatever p1 was equal to originally, it is now equal to 2.  You can do this
with reactions or with any named element, which results in the unfortunate
situation you found, but I never found a satisfactory way to distinguish
between legitimate redefinitions and accidental redefinitions.

-Lucian

**Comment by matthiaskoenig** [comment]
This is an antimony issue / model definition issue and not part of tellurium.
In my opinion expected and correct behavior.

Closing this here.
