### ISSUE TITLE
Support CellML in Bundled Antimony

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#148]
The Antimony package we ship with Tellurium should be compiled with CellML support via the CellML API. This is pending a check to determine that CellML can be distributed along our target distribution channels (i.e. that the libraries it includes are portable and will work on Windows, Mac, and older Linuxes).

**Comment by matthiaskoenig** [comment]
@luciansmith I had the same issues the last weeks. Mainly because the latest cellml library versions did not work on ubuntu 16.04 any more, so it became difficult to link against the cellml libraries.

The trick is to get antimony compiled with the cellml libraries. Only than are the functions available from within tellurium. If one compiles antimony without cellml all the cellml transformation  functions are missing.

Here are scripts how to compile cellml & antimony with cellml
https://github.com/matthiaskoenig/linux-setup/tree/master/scripts
Mainly
https://github.com/matthiaskoenig/linux-setup/blob/master/scripts/cellml-api.sh
how to build the latest cellml-api from source
and
https://github.com/matthiaskoenig/linux-setup/blob/master/scripts/antimony.sh
how to than link antimony against it

**Comment by 0u812** [comment]
Thanks @matthiaskoenig!

**Comment by 0u812** [comment]
The Antimony [wheels](https://github.com/sys-bio/wheelhouse) contain CellML.
