### ISSUE TITLE
Add Dependency Decorators to Functions

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#156]
Global functions in the tellurium module should be decorated with their dependencies so that the runtime can check availability. Ditto for constructors.

**Comment by matthiaskoenig** [comment]
How would you deal with recurrency, i.e you have to check for every function call within every function what their dependencies are to get the full set of dependencies of the function. 
Or alternatively if you change the dependency of a function propagate the dependency to all functions.

I prefer to only have the function definitions if the required packages are available for a very limited subset of functions which have special requirements, like the draw function or notebook stuff.
Otherwise things should fail on runtime if core dependencies are missing, i.e. dependencies which are packed into the win and maxos tellurium distributions.

```
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
```

**Comment by 0u812** [comment]
Currently, in order to use Tellurium, you need to have the complete set of dependencies (i.e. most of the packages listed [here](https://github.com/sys-bio/tellurium/wiki/Packages)). Some of the reviewers for the last manuscript saw this as a major limitation, and I agree with their stance, so I was planning on modularizing Tellurium for the next release. In other words, users should not need all the packages listed [here](https://github.com/sys-bio/tellurium/wiki/Packages) in order to install and use Tellurium.

The dependency checking I am proposing is a usability feature intended to help users who are not experienced in Python figure out which packages they need to install. For example, the `loada` function requires antimony and libroadrunner, so if a user tries to call `loada` without having those packages installed they should get an error message that says something like "this function requires libroadrunner version x.y.z or greater and antimony version x.y.z or greater". This isn't a standard thing to do in Python, but a lot of Linux package managers have this feature. For example, if you try to run a program you don't have installed, most Linux distros will now show something like: 
```
$ konqueror
bash: konqueror: command not found...
Install package 'konqueror' to provide command 'konqueror'? [N/y]
```
I think this greatly enhances usability for novice users. If we could get something similar in Tellurium, that would be great.

I am only planning on adding it to non-reentrant user-facing functions like `loada`. I don't think there will be a significant impact on performance, but I am also going to add a global flag to disable dependency checking.
