### ISSUE TITLE
RuntimeError: error converting document to conserved moieties, at ??0ModelGeneratorContext@rrllvm

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#180]
The following script cases a runtime error:

RuntimeError: error converting document to conserved moieties, at ??0ModelGeneratorContext@rrllvm@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z

Happens when rr.conservedMoietyAnalysis = True

Running

('Version of roadrunner', '1.4.8; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug 10 2016, 15:56:47; LibSBML Version: 5.13.0')

import roadrunner
import tellurium as te

##Test to get Control Coefficients
modelPath = 'Model_update_names1.9.08_24h_G6P_fixed.xml'
r1 = te.loads(modelPath)
sbml_str = r1.getSBML()
rr = te.loads(sbml_str)
<-- Runtime error happens here -->
rr.conservedMoietyAnalysis = True

**Comment by kirichoi** [comment]
I cannot reproduce the error on my machine. I am using roadrunner version 1.4.16. Could you test it out after updating roadrunner?

**Comment by hsauro** [comment]
How do I update libroadrunner?

Herbert

**Comment by hsauro** [comment]
Looks like I just install the latest tellurium.

**Comment by 0u812** [comment]
If you have the old Tellurium distribution, it might be an ordeal 
because roadrunner wasn't installed via pip. To find out, you can run 
this code in a Python prompt:

import pip

pip.main(['install', '--upgrade', 'libroadrunner'])

If that fails, I think you have to manually remove the roadrunner folder 
from site packages. We can help with that.

J Kyle Medley, PhD Student
Bioengineering/BPSD, Sauro Lab
University of Washington, Seattle

**Comment by hsauro** [comment]
Installing Telluirum form the widnows install work and fixed the
conserfvation runtime error.

However just found another bug..creating new issue.

Herbert

**Comment by hsauro** [comment]
Fixed in 1.4.16
