### ISSUE TITLE
Tellurium 2.0.0 feedback/issues

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/tellurium#196]
Hi all, 
here some feedback to the tellurium 2.0.0 interface. Just tried it on Ubuntu 16.04 and here some feedback
## typo
- typo in `Tellurium actions -> Import pyhton script` -> `python` 
- typo `create code cell` -> `Create ...`

## example notebooks missing/confusing
I expected to find some example notebooks, i.e. the notebooks from the publication packaged with the app. When clicking on 
- `File -> Open Example Notebook` 
I expect to see these example notebooks, but currently only very generic notebook examples which is very confusing.
=> drop generic notebook examples, and provide Tellurium publication examples.

Where are the example notebooks of the publication? 
Create an introductory notebook which shows/documents:
- how to get help for functions
- how to get access to the documentation
- how to load/create model
- how to load/create omex archive
- how to create SED-ML experiment and run it
Currently, all the functionality is hidden and one must be expert user to know how to use tellurium, i.e. there must be some information to get started.

There are lots of tellurium example notebooks which should be included.

After opening tellurium for the first time one sits there and does not really know what to do now. Perhaps an introductory text cell at the top of a new notebook giving the basic information like 
- how to load example notebooks
- how to load SBML
....
would be very helpful for a user.

## Save SBML model not working
When creating a model in a model cell via:
```
model test
    J0: S1 -> S2; k1*S1;
    S1 = 10.0; S2 = 0.0;
    k1 = 0.1
end
Success: Model can be accessed via variable test
```
And than trying to save via the save icon in the model cell, 
the menu for saving pops up and after giving a filename I get
`Save SBML /home/mkoenig/Desktop/test1.xml`
but no file is saved on the harddisk.

## Omex archives not loading
I tried loading some omex archives, but just get a generic error that omex could not be loaded:
Some examples are available here, which should be loaded
https://github.com/SED-ML/sed-ml/tree/master/specification/level-1-version-3/examples
Like for instance the following:
https://github.com/SED-ML/sed-ml/blob/master/specification/level-1-version-3/examples/2d-parameter-scan/2d-parameter-scan.omex?raw=true

The error is very generic, it would help to get a detailled error message to know what is the problem, i.e. provide the stack traces if imports are not working of OMEX, SBML and CELL-ML files.

## No phrasedml cell & SED-ML import
There is no option/icon for import SED-ML, also there is no phrased-ml cell type. What is the reason for this?

Some additional things:
- I don't see the `Merge with cell above` icon in the UI depicted in Fig2 of the manuscript draft
- The ubuntu deb installation information is not closing when clicking install, i.e. one gets a deb install dialog and when clicking install the deb package installs (like I see in the console), but the deb UI does not close after installation, or does not show it is installed.

M
edit: I am updating this when I find new things. Feel free to separate in individual issues.

**Comment by matthiaskoenig** [comment]
Some additional things:
- I don't see the `Merge with cell above` icon in the UI depicted in Fig2 of the manuscript draft
- The ubuntu deb installation information is not closing when clicking install, i.e. one gets a deb install dialog and when clicking install the deb package installs (like I see in the console), but the deb UI does not close after installation, or does not show it is installed.

**Comment by 0u812** [comment]
Many thanks for your feedback, Matthias. New binaries are available at [the download page](https://github.com/sys-bio/tellurium#front-end-1-tellurium-notebook). Update on all issues:
* Typos are fixed
* Added five example notebooks, which should give users an idea of how to use the notebook:
  * Quickstart notebook shows a crash course
  * Tutorial notebook shows how to use Antimony and COMBINE archives
  * Inline OMEX notebook has many examples of OMEX cells, from simple to advanced
  * Calzone & Wolf studies reproduce the case studies in the manuscript
  * All notebooks contain narrative explaining how to create/load/save SBML & COMBINE archives, etc
* Save SBML bug is fixed
* Added more specific error message for importing COMBINE archives. Code first tries to import via PhraSEDML, then libSEDML if PhraSEDML fails. PhraSEDML is the problem in the example you mentioned - something to look into later.
* There currently isn't a SED-ML/PhraSEDML cell type because they have to reference external models. We should probably put some more thought into that if we want to support it in the future, as without the COMBINE archive container things get messy.
* The merge button should definitely be working, please open a new issue if not.
* For the installation quirk, it may be an upstream issue for electron-builder. I usually install via `dpkg -i Tellurium_xyz.deb`, which seems to work.
