### ISSUE TITLE
KeyError: 'PATH'

### ISSUE THREAD

**Issue by silviamorins** [sys-bio/tellurium#337]
I am using Tellurium to install carve me. I type in the Python cell
`import tellurium as te
te.installPackage('carveme')`
and in the end I get a message
`KeyError: 'PATH'`
 
I wonder whether I am doing something wrong?

**Comment by hsauro** [comment]
What computer operating system are you using, MAc, Windows, Linux?

Are you using the notebook or spyder edition?

Herbert Sauro

**Comment by silviamorins** [comment]
Thank you for your answer, I'm using a MAC, and the notebook.

Silvia Morini

**Comment by silviamorins** [comment]
Thank you for your answer, I'm using a MAC, and the notebook.

Silvia Morini

**Comment by hsauro** [comment]
One thing I can confirm is that te.installpackage ('carveme') appears to
install correctly on the windows version. I am currently running:

tellurium.getVersionInfo()

[('tellurium', '2.0.8'), ('roadrunner', '1.4.24'), ('antimony', '2.9.4'),
('libsbml', '5.15.0'), ('libsedml', '403'), ('phrasedml', '1.0.8')]

Herbert Sauro

**Comment by 0u812** [comment]
One thing I noticed from looking at the [carveme package](https://pypi.python.org/pypi/carveme/1.1.0) is that it appears to be Python 2 only. Is this in fact the case? The notebook version of Tellurium runs on Python 3, so that would be one factor preventing it from working.

I'm currently working on adding support for multiple kernels (e.g. Python2) to the notebook.

**Comment by hsauro** [comment]
But I assume I am also running Python 3 on my windows verison of the
notebook and carveme installed there ok.
Herbert

**Comment by kirichoi** [comment]
This sounds like a environment variable issue. Could you do something like:
```
import os
print(os.environ["PATH"])
```

**Comment by 0u812** [comment]
That is puzzling. Are you also able to import the package?

**Comment by hsauro** [comment]
I can import the package on the windows version of the notebook.

H

**Comment by 0u812** [comment]
@hsauro I'm not sure why it seems to work for you but that seems to be a fluke. I tried installing it but I can't import it because it appears to be designed for Python2-only and throws errors that are clearly caused by Python3 incompatibility.

@silviamorins unfortunately it seems that it currently isn't possible to use the `carveme` package in the Tellurium notebook viewer because of the aforementioned Python version incompatibility. However, you can install Tellurium into a pre-existing Python2 installation via the terminal (the terminal app is in  /Applications/Utilities/ if you need help finding it - you should also be able to open it from Spotlight):
```
$ pip install tellurium
```
You can then use it with Jupyter. If the above pip command fails, could you please provide more info about your setup, e.g. did you install Python from [python.org](https://www.python.org/) or are you using the Python that came with your system?

**Comment by hsauro** [comment]
Actually you're right importing it doesn't work:

--------------------------------------------------------------------------
ModuleNotFoundError Traceback (most recent call last)
<ipython-input-2-5242e1ea1fe5> in <module>() ----> 1 import carveme
~\AppData\Roaming\Tellurium\telocal\python-3.6.2\lib\site-packages\carveme\__init__.py
in <module>() 1 import os ----> 2 from ConfigParser import ConfigParser 3
from framed import set_default_solver, set_default_parameter, Parameter 4 5
__version__ = '1.1.0' ModuleNotFoundError: No module named 'ConfigParser'

Herbert

**Comment by hsauro** [comment]
Do we have a resolution for this yet?

**Comment by kirichoi** [comment]
If the issue is indeed with incompatible Python versions, there's no solution unless the devs decide to add support for Python 3.6. The only workaround is given by Kyle, which is installing a Python 2.7 distro (e.g. anaconda) and configuring it to use Tellurium.

**Comment by hsauro** [comment]
In other words we don't actually know what the problem is but there is a
workaround?

Herbert

**Comment by kirichoi** [comment]
It means that solving this problem, even if it is not a compatibility issue, will end you up in a Python environment that still cannot use `carveme` package. Better to spend time in configuring a Python 2.7 environment in that case. 
For the original issue, I have a feeling that it's a machine specific issue due to some messed up configurations.

**Comment by silviamorins** [comment]
Sorry for having been a little away from the discussion. It can also be a messed up configuration from my side - I'm trying to solve the problem and let you know what comes up. thank you for your advices!
