### ISSUE TITLE
Uninstalling Tellurium notebook does not remove files

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#351]
On Windows, even after 'uninstalling' Tellurium notebook, the core seems to be untouched at `Users\AppData\Roaming\Tellurium`

**Comment by 0u812** [comment]
I looked into this when I was originally writing the code. There isn't a cross-platform way to fix this afaik. On Mac, to uninstall an app, you just drag it to the bin. There's no opportunity for scripts to run to clean up files etc. On the other hand, options for platform-specific scripts are usually pretty limited in Electron, so even if there was a platform-specific fix I doubt there's a way to implement it...

**Comment by 0u812** [comment]
In 2.0.14 it does overwrite the old Python environment with a new one, however.

**Comment by hsauro** [comment]
That's sounds like sloppy work by the Electron developers. Applications
shouldn't leave their detritus after an uninstall. Imagine if every
application did that, a user's harddrive would just fill up with unwanted
files. After an uninstall the only thing that tends to be left behind are
user created files, since the uninstaller isn't aware of those. Anything
installed by the installer is removed. I don't know how Electron
applications work but I assume they can be installed using standard
installers? If it comes with its own installers then  it sounds like very
poor design on their part. Using standard installer on Windows would mean a
clean uninstall.

On the Mac does the application copy files outside where it is installed?
In not then dragging to the trash would be sufficient.

Herbert

**Comment by kirichoi** [comment]
That's quite unfortunate, especially because the installation is quite large (~2 GB), and the install directory is generally hidden for the most users.  From a quick search, there might be a way to remove AppData on uninstall through some custom script. Or maybe we should switch to NSIS instead for windows installer specifically?

**Comment by hsauro** [comment]
If it's possible, I agree use either nsis or inno setup. The later is
particularly easy to use. We can't leave 2gb on a user machine after an
uninstall.

Herbert

**Comment by 0u812** [comment]
Again, on the Mac, it isn't possible to do this due to the operating system not providing a way. On Linux it isn't possible for different reasons. It might be possible on Windows through some sort of custom script, but that would only cover 1/3 of the supported platforms. I'll look into it to see if there is a way on that one platform...

**Comment by kirichoi** [comment]
On Mac ans Linux, I presume you are supposed to delete the directory? You can do the same on Windows, but the problem is Tellurium is installed to appdata, which is a hidden directory. Probably the majority of Windows users doesn't even know that such directory exists. I think we can simply add a documentation somewhere (maybe even add a notice in the notebook) and call it a day.

**Comment by hsauro** [comment]
The professional approach is to do it properly, and in the case of Windows
we know how to do it unless Electron apps are doing something very weird.
If you pick the right installer, e.g. Innosetup, there aren't even any
scripts to write, innosetup knows what files it installed and where they
are stored and it will automatically uninstall the files.

Kyle, on the Mac and Linux are you suggesting that these OSes copy files
out of the install directory and not record this information?

As I said we can't leave 2gb of material on a user's hard drive when they
uninstall. On windows that is frowned upon, on the Mac and Linux things may
be different and users aren't so worried about accumulating dead installs.

Herbert

**Comment by 0u812** [comment]
The install directory on Mac/Linux isn't user-writable, so the viewer has to copy files to a user-writable directory (otherwise the user can't install new Python packages, which is one of the requirements the notebook viewer was designed to satisfy). Since the user-writable directory is outside of the installation directory, it doesn't get deleted when you uninstall the app. Windows is different so it might be possible to run a custom script on uninstall to remove the extra files.

**Comment by hsauro** [comment]
On windows you should be able do a clean uninstall, it won't uninstall user
created files as it won't know about those, but that's the user
responsibility. I feel sorry for the Mac users who over time have to put up
with accumulated detritus

Herbert
