### ISSUE TITLE
Change to api on siumulate?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#377]
Looks like there was a change to the simulate API? I get this error message:

TypeError: simulate() got an unexpected keyword argument 'integrator'

Can we restore this?

import tellurium as te
import pylab
rr = te.loada ('''
    compartment V1 = 1, V2 = 10;
    var S1 in V1;
    var S2 in V2;
    S1 -> S2; A*k1*S1;
    S2 -> S1; A*k2*S2;
    S1 = 10; S2 = 0;
    k1 = 0.4; k2 = 0.4; A = 1;
''')
result = rr.simulate(1, 40, 100, integrator="cvode")
pylab.xlim([0,30])
te.plotWithLegend(rr, result)

**Comment by 0u812** [comment]
Just to recap my current understanding, to the best of my recollection, we simplified the `simulate` function several years ago at the urging of @matthiaskoenig and with your approval. I think the reason was that the `simulate` function had a huge number of arguments and very complicated logic for evaluating those arguments based on different position and keyword combinations. This also made the documentation quite complex, and anyone just learning the package would be confronted with a wall of documentation for one of the most commonly used functions. Of course, I'm not opposed to adding additional arguments, but I just hope it's not a change we will end up reverting. Please let me know if you'd still like to go ahead with this.

**Comment by hsauro** [comment]
Ok lets forget about this one, what I can do is put an errata on the book textbook website instead.

Herbert
