### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by sfinck187** [sys-bio/tellurium#430]
I installed the most recent version of Tellurium using the 64 bit windows installer on a brand new Dell G7 with Windows 10.  

Jupyter notebook works fine.  I click on the Spyder IDE and then nothing happens.  No error, no program launch, just nothing.  Thoughts?

I've uninstalled and reinstalled.  Re-booted and tried again . . .

**Comment by sfinck187** [comment]
![image](https://user-images.githubusercontent.com/47158610/51942365-7e48fa80-23dc-11e9-9449-12d74182fc42.png)

**Comment by sfinck187** [comment]
Not sure what "'Analysis' is not recognized" is referring to.  A path not defined for one of the startup scripts?

**Comment by kirichoi** [comment]
Would you mind zipping the whole `scripts` folder and upload here? I think github allows zip files on their issue tracker.

**Comment by sfinck187** [comment]
[scripts.zip](https://github.com/sys-bio/tellurium/files/2809896/scripts.zip)

**Comment by sfinck187** [comment]
![image](https://user-images.githubusercontent.com/47158610/51946140-51014a00-23e6-11e9-9d7a-1b8505da33aa.png)

**Comment by kirichoi** [comment]
Well, I am guessing you are using cmd not `Winpython command prompt` here? Can you check what you get if you just type `path`? (make sure you are using normal command prompt please)

**Comment by sfinck187** [comment]
Hey Kiri, thanks for your help so far.  I promise I'm not trying to be difficult.  Here's a screenshot of the output of typing echo %PATH% in Winpython command prompt:
![image](https://user-images.githubusercontent.com/47158610/51948168-1949d080-23ed-11e9-8f13-6e4c24fdfeef.png)
And here's "path" in normal Windows command prompt:
![image](https://user-images.githubusercontent.com/47158610/51948231-5615c780-23ed-11e9-8b04-c4b3defcc7c9.png)

**Comment by kirichoi** [comment]
Thanks a lot. 

I think I know what the issue is. `&` syntax has a very specific meaning which is used here. I don't know what `QuantStudio Design & Analysis Software` is, but you might want to remove it from the PATH variable. 

To do so, search for `Edit the system environment variables` or go to `control panel -> system -> advanced system settings` and press `environment variables`. Under `System variables`, there should be a variable called `path` which you click and press `edit`. Once you do that, a new window will pop up, where you can look for the specific path that is malformed (something with `QuantStudio Design & Analysis Software`) and delete it. 

Once you have done that, try running Tellurium again and let me know what happens.

**Comment by sfinck187** [comment]
Worked like a charm.  Thanks so much!

**Comment by kirichoi** [comment]
No problem. Glad it worked! :)
