### ISSUE TITLE
getoODEsFromModel crashes

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#474]
The following script crashes

import tellurium as te
import roadrunner

r = te.loada("""
     S1 -> S2; k1*S1;
     k1 = 0.1;
     S1 = 1; S2 = 0
""")

print (te.getODEsFromModel(r))

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tesbml\libsbml.py", line 98, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))

AttributeError: 'Species' object has no attribute 'boundary_condition'

Problem with libsbml or something else?

**Comment by luciansmith** [comment]
This also failed for me, which turned out to be because 'boundary_condition' is not... anything.  The correct way to get that attribute is 'getBoundaryCondition()'.

I have fixed this in the develop branch of tellurium, but you should be able to fix it yourself, too.  From Spyder, when you get the error:


  File "D:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\utils\misc.py", line 250, in toString
    if not self.model.getSpecies (index).boundary_condition:

Click on the filename, and change boundary_condition to 'getBoundaryCondition()':

            if not self.model.getSpecies (index).getBoundaryCondition():

**Comment by hsauro** [comment]
That works thanks. Sounds like it never worked

**Comment by luciansmith** [comment]
I know!  I guess that function was never tested.
