### ISSUE TITLE
Memory leak in Antimony

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#551]
I've been running a large number of roadrunenr instances by generating the SBML from Antimony then loading the SBML. I've discovered there is a significant memory leak in Antimony such that I end up using 10s of Gb of memory and on rate occasions the entire spyder IDE just vanishes I think due to an out of memroy error. I'm using 20,000 models at a time and are generated on the fly in antimony format.

You can monitor the memory usage using the following scripts, I just watch the task manager memory consumption. Memory consuption continuous increases over time. This was run outside spyder from the windows terminal to eliminate any potential sypder issues.

Using latest tellurium windows installer. As an example if you run the loop with 50,000 models, the memory usage is at 16 Gb, and climbing. You can imagine that everntually it runs out of memory.

As a check you can run the second script which bypasses antimony and there is no leak at all so the leak must be in antimony.

import tellurium as te

With leak:

```
astr = """
S1 -> S2; k1*S1
S2 -> S3; k2*S2;
S3 -> S4 + S5; k3*S3;

k1 = 0.1; k2 = 0.2; k3 = 0.4
S1 = 10
"""

for i in range (20000):
   r = te.loada(astr)
   print (i)
```

Without leak:

```
import roadrunner
import antimony

astr = """
S1 -> S2; k1*S1
S2 -> S3; k2*S2;
S3 -> S4 + S5; k3*S3;

k1 = 0.1; k2 = 0.2; k3 = 0.4
S1 = 10
"""
antimony.loadAntimonyString(astr)
sbmlstr = antimony.getSBMLString()

for i in range (20000):
   r = roadrunner.RoadRunner (sbmlstr)
   print (i)
```

**Comment by luciansmith** [comment]
This turned out to not be a 'leak' in the traditional sense, but improper use of the Antimony library inside Tellurium.  Because you can store and load models separately using libantimony, it keeps a record of everything you've stored so you can load it again, until you call 'clearPreviousLoads'.  In the past, tellurium used to call that function (as far as I recall), but somehow it got dropped in more recent versions.  I'll fix that, and create a new release.

**Comment by luciansmith** [comment]
Now fixed!
