### ISSUE TITLE
Some Tellurium Examples No Longer Work

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#57]
From Joe: Looks like there has been some refactoring with IPython so some examples no longer work.
```
ubuntu@ubuntu:~/TelluriumStack$ python tellurium/examples/tellurium-files/computeSteadyState.py
/usr/local/lib/python2.7/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "tellurium/examples/tellurium-files/computeSteadyState.py", line 7, in <module>
    import tellurium as te
  File "/usr/local/lib/python2.7/dist-packages/tellurium/__init__.py", line 8, in <module>
    import widgets
  File "/usr/local/lib/python2.7/dist-packages/tellurium/widgets/__init__.py", line 2, in <module>
    from _parameter_slider import ParameterSlider
  File "/usr/local/lib/python2.7/dist-packages/tellurium/widgets/_parameter_slider.py", line 1, in <module>
    from IPython.html.widgets import interact
ImportError: cannot import name interact
```

**Comment by hsauro** [comment]
Wish they wouldn't change stuff....

H

**Comment by kirichoi** [comment]
Do we know which version of IPython he is running?

**Comment by 0u812** [comment]
He didn't say, but I forwarded his original email to you so you can 
follow up if you like.

**Comment by kirichoi** [comment]
A simple solution for him would be to install a library called `ipywidgets`. With this library installed, the code will run fine because IPython team did ensure backwards compatibility. Obviously, we will need to include few additional packages with our distribution in the future if we do package IPython 4.0, but I do not think this is actually a problem at our end. It is quite bizarre though, IPython has been split up into numerous small packages and I do not even have the numbers for it.
