### ISSUE TITLE
Mac binary missing a dependency -  ipywidgets module 

### ISSUE THREAD

**Issue by jamesscottbrown** [sys-bio/tellurium#79]
I've just downloaded the Mac binary of tellurium, and tried running the command `import tellurium as te`. This fails with the following  traceback:

    Traceback (most recent call last):    

      File "<ipython-input-5-68f36c26b7d9>", line 1, in <module>
        import tellurium as te    

      File "/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/__init__.py", line 8, in <module>
        import widgets    

      File "/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/widgets/__init__.py", line 2, in <module>
        from _parameter_slider import ParameterSlider    

      File "/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/widgets/_parameter_slider.py", line 6, in <module>
        import ipywidgets    

    ImportError: No module named ipywidgets

I was at least able to copy ~/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium into ~/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ and thus obtain a working installation of the tellurium module that I can use form an ipython notebook, which I had previously been struggling to get:

*  trying to run the contents of antimony-v2.7-osx-64.tar.gz (downloaded from sourceforge) gave an error ('Fatal Python error: PyThreadState_Get: no current thread' - presumably due to using a different python version)
* the archive antimony_src_v2.8.tar.gz (downloaded from sourceforge) did not extract correctly
* I successfully checked out the source from the sourceforge SVN repository, but then found I would need to install many libraries as dependencies before it would compile

**Comment by matthiaskoenig** [comment]
Hi James,
for now you can fix this easily via installing the dependency via
```
pip install ipywidgets
```

@kirichoi 
When packing Tellurium you have to at least include the requirements listed in `requirements.txt` for tellurium. 
`requirements.txt` should state all python dependencies you pack with tellurium so on is able to create a virtual environment on linux (win/mac) which reflects the python packages packed with the installer.

I updated the information on:
https://github.com/sys-bio/tellurium/wiki/Packages
@kirichoi you should add all packages and the **versions  numbers** you are packing in the document & distinguish what is needed to build tellurium & what is packed in addition in Tellurium.

this is part of #75

**Comment by jamesscottbrown** [comment]
>  for now you can fix this easily via installing the dependency via
>    pip install ipywidgets

This doesn't work, as it would install the package for my normal python installation, whereas the Spyder application bundle includes its own python binary (`~/Applications/Spyder-Py2.app/Contents/MacOS/python`), with its own directory of installed modules (`~Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages`), and a path that will not find modules installed for other python installations:

    In [7]: import sys    

    In [8]: sys.path
    Out[8]: 
    ['',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python27.zip',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-darwin',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac/lib-scriptpackages',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-tk',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-old',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-dynload',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages.zip',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages',
     '/Users/jsb/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/extensions',
     '/Users/jsb/.ipython']

There are a couple of obvious hacks that I tried which didn't work:

* In principle I could download `ipwidgeys` from PyPi then run it's `setup.py` using `~/Applications/Spyder-Py2.app/Contents/Resources/lib/python2.7`, but this fails:

    ~/Downloads/ipywidgets/ $ ~/Applications/Spyder-Py2.app/Contents/MacOS/python setup.py install
    Could not find platform independent libraries <prefix>
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    ImportError: No module named site

(however, this approach might work with if environmental variables are fiddled with)

* I could try using the module installed by my  system-wide python install, by appending to `sys.path` before running the import. However, this fails because I am using a more recent version of IPython than the spyder bundle (4.0.1 vs. 3.2.0)

**Comment by matthiaskoenig** [comment]
Hi James, 
I see. 
@kirichoi should repack as soon as possible with all dependencies which will solve the issue
The problem arose, because I moved the imports to the header of the files. 
Before the import was only performed if someone tried to use the function with the import (so was broken, but nobody noticed, because the function was never called in any code).

There are a handful of import dependencies in the code which are not fullfilled (like ipywidgets), but should be as soon as repacked. Sorry for the inconvenience: I decided to put the imports in the open to be able to fix these until now hidden issues.

**Comment by matthiaskoenig** [comment]
@hsauro, @0u812 , @kirichoi 
Related to this issue: Tellurium states: 
> The environment is extensible as the users can install additional Python libraries if necessary

How would one install additional libraries, for instance here `ipywidget` in the tellurium python environment? I could not find any information about this. For instance I want to have
`pandas`
in spyder. Could you provide a code example of how to do this.

**Comment by hsauro** [comment]
The reason we use a completely separate  Python distribution is that we
found early on that users did not like it at all if we interfered with
their own distriubution, in fact it caused some user setups (they have
specific versions of things like numpy installed) to break so we decided to
avoid any issues by having a separate installation and we've not had any
problems since. Problem now is how do users install other packages into our
distribution.

Kiri, kyle, maybe you have some ideas?

Herbert

**Comment by kirichoi** [comment]
Sorry for the confusion. We are aware of this issue and Kyle will put up a new binary soon.

@matthiaskoenig : Windows version of Tellurium comes with a command prompt just for the separate Python environment. Users can follow standard installtion procedure i.e. using `pip` to install packages.  For Mac, any insights Kyle @0u812 ?
I was writing up a document for it but it never got put on the website.

**Comment by 0u812** [comment]
Updating the tellurium package bundled with the OS X binary was a bit 
auspicious. I put the fires out by downgrading. No time to work on this 
right now, gotta work on the plugins.

**Comment by kirichoi** [comment]
@0u812 I support your decision. The transition was suppose to happen on the next release.

**Comment by jamesscottbrown** [comment]
Here is a more complete list of missing dependencies:

Mac is missing:  ipywidgets, pygraphviz, tephrasedml, SedmlToRr, sbml2matlab

Windows is missing: pygraphviz

**Comment by matthiaskoenig** [comment]
see also https://github.com/sys-bio/tellurium/wiki/Packages


On Tue, Jan 26, 2016 at 2:16 PM, James Scott-Brown <notifications@github.com
> wrote:

> Here is a more complete list of missing dependencies:
>
> Mac is missing: ipywidgets, pygraphviz, tephrasedml, SedmlToRr, sbml2matlab
>
> Windows is missing: pygraphviz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/79#issuecomment-175007143>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by matthiaskoenig** [comment]
The documentation & manuscript state clearly that one can install additional packages with pip. See for instance at
http://tellurium.analogmachine.org/

> In addition other tools kits such as matplotlib and NumPy are used to provide additional analysis and plotting support. **When you need to add a another package, te. comes with pip, so you can easily pip install package whenever you need them.**

The 
```
pip install ipywidgets
```
should work on Mac & Win or it has to be removed from the documentation. 

In my opinion the pip install is a crucial feature, otherwise you loose all the power of python. Depending on the research question you need to load custom libraries.
I currently work on linux where I just build and pack all the dependencies in a virtual environment in which I can pip install. So it is no issue there. But I am planing to give some demonstration course of Tellurium on Win/Mac in the next few weeks and installing custom packages would be essential.

**Comment by matthiaskoenig** [comment]
What is the status on this?
I think this was fixed already in the last releases. 
Did anybody inform @jamesscottbrown ?
If fixed, close the issue.

**Comment by hsauro** [comment]
Kyle should know.

**Comment by 0u812** [comment]
I thought we decided not to include Jupyter in the Mac version because you use the Spyder IPython console in Spyder instead. Once we have a complete set of conda packages people can use tellurium from a notebook or whatever, but for this release we're still using the dmg, so no Jupyter.

On March 9, 2016 9:41:36 AM PST, Herbert Sauro <notifications@github.com> wrote:
>Kyle should know.
>
>On Wed, Mar 9, 2016 at 3:47 AM, Matthias König
><notifications@github.com>
>wrote:
>
>> What is the status on this?
>> I think this was fixed already in the last releases.
>> Did anybody inform @jamesscottbrown
><https://github.com/jamesscottbrown> ?
>> If fixed, close the issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/tellurium/issues/79#issuecomment-194259755>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/79#issuecomment-194418492

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by matthiaskoenig** [comment]
Yes, no including.

But the original issue is fixed for long now via catching the ImportError and can be closed. Just looked in the codebase and all occurences of ipywidget are handled.
I will close the issue. Please reopen if still problems.
