### ISSUE TITLE
Notebooks module raises ImportError in Spyder internal console

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#84]
One of the dependencies of new package `bioservices` called `easydev` raises ImportError for some reason when tellurium is imported in Spyder internal console. This is a problem for Spyder plugins using tellurium. One way to circumvent this is to not enforce `notebooks` in such way:
```
try:
    import notebooks
except ImportError:
    pass
```
since everything works fine in both IPython and Python console and Spyder plugins does not depend on `notebooks` module.

**Comment by matthiaskoenig** [comment]
Hi Kiri,
I would prefer to have as little import as possible when doing
```
import tellurium as te
```

The namespace was extremely cluttered via all the
```
from something import *
```
I already tried to clean this a bit.

I only put the
```
import notebooks
```
in the __init__.py of tellurium because it was there before and you do a
```
from notebooktools import *
```
I thought you need this for something in tellurium so left it there.

If the notebooktools are only used in notebooks but never in tellurium
spyder we should not import them at all.

M


On Fri, Feb 12, 2016 at 11:43 PM, Kiri Choi <notifications@github.com>
wrote:

> One of the dependencies of new package bioservices called easydev raises
> ImportError for some reason when tellurium is imported in Spyder internal
> console. This is a problem for Spyder plugins using tellurium. One way to
> circumvent this is to not enforce notebooks in such way:
>
> try:
>     import notebooks
> except ImportError:
>     pass
>
> since everything works fine in both IPython and Python console and Spyder
> plugins does not depend on notebooks module.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/84>.
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by kirichoi** [comment]
`notebooks` module is not only for IPython notebooks but also for ontology and species search through biomodels. I will leave it as is, but implement my suggestions as a temporary solution since it breaks things.

**Comment by 0u812** [comment]
What does it break?

On February 18, 2016 11:21:45 AM PST, Kiri Choi <notifications@github.com> wrote:
>`notebooks` module is not only for IPython notebooks but also for
>ontology and species search through biomodels. I will leave it as is,
>but implement my suggestions as a temporary solution since it breaks
>things. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/84#issuecomment-185873611

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by kirichoi** [comment]
It used to break all the plugins as it tried to import tellurium. No need for plugins to import `notebooks` though.
