### ISSUE TITLE
Add link to Matthias' course to course page

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#85]
Add a link to Matthias' course to the course page on telluirum.analogmachine.org.

PS I can't seem to log into tellurium.analogmachine.org, wrong password or user name?

**Comment by 0u812** [comment]
I have access to the site so I went ahead and added it. I don't think we know the official title of his course so I just put "systems biology modeling course" for now. Will update as new information comes in.

Herbert, do you know how I can give you access to the site? I don't see a place to add new members on the dashboard...

**Comment by hsauro** [comment]
You need to be administrator to add new people. I should be there however.

H

**Comment by matthiaskoenig** [comment]
The full documentation is in 
```
tellurium/docs/_build
```
This folder should be hosted on the tellurium page. 

Currently, the documentation is also automatically updated on 
tellurium.readthedocs.org
but unfortunately it is not possible to build the apidoc there (due to missing python packages for most of the tellurium dependencies).

In the local build, i.e. the _build folder you have a full API documentation (see for instance by clicking on API or tellurium methods in the index.html). So it would be much better to just move the content of the `_build` folder on the tellurium page instead of linking.

**Comment by matthiaskoenig** [comment]
Closing this. All examples are part of the documentation.
This is handled via #144
