### ISSUE TITLE
Default path for getTelluriumVersion()

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#94]
Currently, `getTelluriumVersion` calls 

`os.path.join(os.path.dirname(__file__), '..', 'VERSION.txt')` which causes problem in Windows.
Is there a reason why double dots are there?

**Comment by matthiaskoenig** [comment]
Yes. It is the platform-independent way to go up one directory.
http://stackoverflow.com/questions/17885516/moving-up-one-directory-in-python

The combination of os.path.dirname(__file__), '..' and os.path.join should
resolve the VERSION.txt on Mac, Linux and OS without problems.
Always use `os.path.join` to join the parts of paths instead of \\.

On Fri, Feb 19, 2016 at 2:01 AM, Kiri Choi <notifications@github.com> wrote:

> Currently, getTelluriumVersion calls
>
> os.path.join(os.path.dirname(__file__), '..', 'VERSION.txt') which causes
> problem in Windows.
> Is there a reason why double dots are there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/tellurium/issues/94>.
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480

**Comment by kirichoi** [comment]
I understand what is going on. In case of Tellurium distribution, VERSION.txt is often placed under the same directory as tellurium.py, unlike the repo. I will add a line or two to check both paths.
